### ISSUE TITLE
Getter properties not appearing in State inspector

### ISSUE THREAD

**Issue by johnhamm** [anton-lunev/angular-state-inspector#1] opened 2018-08-31 20:32 UTC
Love this extension!

One thing though - can you show getter properties in the state inspector?  I have @computed getter properties in my state that don't appear currently, but they do appear in ng.probe($0).componentInstance.

Thanks!

**Comment by anton-lunev** [comment] 2018-09-02 02:01
Hi @johnhamm, thank you for your feedback. 
Could you please make a simple demo where getters don't appear. Do you mean you don't see getter at all or that getter value appears only after click on (...)? 
Actually it should show exactly the same data as console does, because I call ng.probe($0).componentInstance in extension.

**Comment by anton-lunev** [comment] 2019-12-30 02:28
Closing as outdated. 
Feel free to reopen in case it's still reproducible.

**Closed as completed by anton-lunev** 2019-12-30 02:28 UTC
